// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lmm_maximize_cpp
DataFrame lmm_maximize_cpp(NumericVector y, NumericMatrix x, int addintercept);
RcppExport SEXP MESS_lmm_maximize_cpp(SEXP ySEXP, SEXP xSEXP, SEXP addinterceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type addintercept(addinterceptSEXP);
    __result = Rcpp::wrap(lmm_maximize_cpp(y, x, addintercept));
    return __result;
END_RCPP
}
// lmm_Maximize_cpp
List lmm_Maximize_cpp(NumericVector y, NumericMatrix x, List vc, int maxiter, int method);
RcppExport SEXP MESS_lmm_Maximize_cpp(SEXP ySEXP, SEXP xSEXP, SEXP vcSEXP, SEXP maxiterSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type vc(vcSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    __result = Rcpp::wrap(lmm_Maximize_cpp(y, x, vc, maxiter, method));
    return __result;
END_RCPP
}
// mfastLm_cpp
DataFrame mfastLm_cpp(NumericVector y, NumericMatrix x, int addintercept);
RcppExport SEXP MESS_mfastLm_cpp(SEXP ySEXP, SEXP xSEXP, SEXP addinterceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type addintercept(addinterceptSEXP);
    __result = Rcpp::wrap(mfastLm_cpp(y, x, addintercept));
    return __result;
END_RCPP
}
