# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximize linear mixed model with user-specified covariance matrices
#'
#' @description Fast computation of simple regression slopes for each predictor represented by a column in a matrix
#' @param y A vector of outcomes.
#' @param x A design matrix of regressor variables. Must have the same number of rows as the length of y.
#' @param vc A list of fixed variance-covariance matrices
#' @param maxiter Maximum number of iterations
#' @param REML A logical that determines if restricted maximum likelihood (REML - the default) or maximum likelihood (ML) 
#' @param tolerance The Maximum number of iterations
#' @return A data frame with two variables: coefficients and stderr that gives the slope estimate and corresponding standard error for each column in x.
#' @author Claus Ekstrom <claus@@rprimer.dk>
#' @export
lmm_Maximize_cpp <- function(y, x, vc, maxiter = 25L, REML = TRUE, tolerance = 0.000001, reparam = FALSE, scale = TRUE) {
    .Call('MESS_lmm_Maximize_cpp', PACKAGE = 'MESS', y, x, vc, maxiter, REML, tolerance, reparam, scale)
}

#' Fast marginal simple regresion analyses
#'
#' @description Fast computation of simple regression slopes for each predictor represented by a column in a matrix
#' @param y A vector of outcomes.
#' @param x A matrix of regressor variables. Must have the same number of rows as the length of y.
#' @param addintercept A logical that determines if the intercept should be included in all analyses (TRUE) or not (FALSE)
#' @return A data frame with two variables: coefficients and stderr that gives the slope estimate and corresponding standard error for each column in x.
#' @author Claus Ekstrom <claus@@rprimer.dk>
#' @export
mfastLm_cpp <- function(y, x, addintercept) {
    .Call('MESS_mfastLm_cpp', PACKAGE = 'MESS', y, x, addintercept)
}

#' Fast extraction of matrix diagonal
#'
#' @description Fast extraction of matrix diagonal
#' @param x The matrix to extract the diagonal from
#' @return A vector with the diagonal elements
#' @details Note this function can only be used for extraction
#' @author Claus Ekstrom <claus@@rprimer.dk>
qdiag <- function(x) {
    .Call('MESS_qdiag', PACKAGE = 'MESS', x)
}

#' Fast quadratic form computation
#'
#' @description Fast computation of a quadratic form  t(x) %*% M %*% x
#' @param x A matrix with dimensions n*k.
#' @param M A matrix with dimenions n*n. If it is to be inverted then the matrix should be symmetric and positive difinite (no check is done for this)
#' @param invertM A logical. If set to TRUE then M will be inverted before computations (defaults to FALSE)
#' @param transposex A logical. Should the matrix be transposed before computations (defaults to FALSE).
#' @return A matrix with dimensions k * k giving teh quadratic form
#' @author Claus Ekstrom <claus@@rprimer.dk>
#' @export
quadform <- function(x, M, invertM = FALSE, transposex = FALSE) {
    .Call('MESS_quadform', PACKAGE = 'MESS', x, M, invertM, transposex)
}

#' Fast computation of trace of matrix product
#'
#' @description Fast computation of the trace of the matrix product trace(t(A) %*% B)
#' @param A A matrix with dimensions n*k.
#' @param B A matrix with dimenions n*k.
#' @return The trace of the matrix product
#' @author Claus Ekstrom <claus@@rprimer.dk>
#' @export
tracemp <- function(A, B) {
    .Call('MESS_tracemp', PACKAGE = 'MESS', A, B)
}

