# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mfastLm_cpp <- function(y, x, addintercept) {
    .Call('MESS_mfastLm_cpp', PACKAGE = 'MESS', y, x, addintercept)
}

MLtest <- function() {
    .Call('MESS_MLtest', PACKAGE = 'MESS')
}

